package com.shiptrackpro.entity;

import com.shiptrackpro.enums.ShipmentStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;

/**
 * JPA entity representing a shipment in the ShipTrack Pro platform.
 *
 * <p>Maps to the {@code shipments} table in PostgreSQL and models a package
 * moving from a sender to a receiver, including sender/receiver contact
 * details, package information, current delivery status, and audit
 * timestamps.</p>
 */
@Getter
@Setter
@ToString
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
@Entity
@Table(name = "shipments")
public class Shipment {

    /** Surrogate primary key, generated by the PostgreSQL identity column. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /** Unique, customer-facing tracking code for this shipment. */
    @Column(name = "tracking_number", nullable = false, unique = true, length = 50)
    private String trackingNumber;

    /** Full name of the person/business sending the package. */
    @Column(name = "sender_name", nullable = false, length = 150)
    private String senderName;

    /** Contact phone number of the sender. */
    @Column(name = "sender_phone", nullable = false, length = 20)
    private String senderPhone;

    /** Full name of the person/business receiving the package. */
    @Column(name = "receiver_name", nullable = false, length = 150)
    private String receiverName;

    /** Contact phone number of the receiver. */
    @Column(name = "receiver_phone", nullable = false, length = 20)
    private String receiverPhone;

    /** Category of package, e.g. "Document", "Parcel", "Fragile". */
    @Column(name = "package_type", length = 50)
    private String packageType;

    /** Weight of the package in kilograms. */
    @Column(name = "package_weight")
    private Double packageWeight;

    /** Pickup / origin location for the shipment. */
    @Column(name = "origin", length = 255)
    private String origin;

    /** Final destination city/region for the shipment. */
    @Column(name = "destination", length = 255)
    private String destination;

    /** Full delivery address for the receiver. */
    @Column(name = "delivery_address", length = 255)
    private String deliveryAddress;

    /**
     * Current lifecycle status of the shipment. Persisted as its enum name
     * (e.g. {@code "IN_TRANSIT"}) rather than an ordinal, so the column
     * stays readable and stable even if enum constants are reordered.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "shipment_status", nullable = false, length = 30)
    private ShipmentStatus shipmentStatus;

    /** Timestamp when this shipment record was first created. Immutable after insert. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp when this shipment record was last modified. */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * JPA lifecycle callback invoked automatically before the entity is
     * first persisted. Stamps both {@code createdAt} and {@code updatedAt},
     * and defaults the status to {@link ShipmentStatus#CREATED} if none was
     * supplied.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.shipmentStatus == null) {
            this.shipmentStatus = ShipmentStatus.CREATED;
        }
    }

    /**
     * JPA lifecycle callback invoked automatically before every update.
     * Refreshes {@code updatedAt} so callers never have to set it manually.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

}

