spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/shipment_tracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Balaji@25

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

jwt.secret=VGhpc0lzQVNlY3JldEtlckZvclNoaXBUcmFja1Byb0pXVEF1dGhlbnRpY2F0aW9uMTIzNDU2
jwt.expiration=86400000
spring.security.oauth2.client.registration.google.client-id=1019807471212-tik8o5cguu0uj65m1ke5r2fk9i7q4684.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.mail.username=balajikrishnapillai01@gmail.com
spring.mail.password=Balaji@2005
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

google.maps.api-key=AIzaSyAEqs7_2CT49g297KuQ86TBWgx1UP-g434
google.maps.default-center=12.9716,77.5946
